version: "3.8"

services:
  ml_hw_container:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    container_name: jupyter
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"
    volumes:
      - ../..:/workspaces:cached
