version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: ./devcontainer/Dockerfile
    container_name: jupyter
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"
    volumes:
      - ../..:/workspaces:cached